# Name of workflow to be displyed on Github Console
name: CI/CD Notify on Slack

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # "build" workflow
  build:

    name: Build and Test application
    #The type of runner on which job will run
    runs-on: ubuntu-latest

    # steps can run commands, setup tasks or run an action
    steps: 
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: installing requirements
        uses: py-actions/py-dependency-install@v2      
        with:
          path: "./requirements.txt"
      - name: Heroku deploying stage
        uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_app_name: ci-me-dice-stage
          heroku_email: "salitomeyo16@gmail.com"
          heroku_api_key: ${{secrets.HEROKU_AUTH_TOKEN}}
      - name: unit test
        run: |
          python3 -m venv venv
          venv/bin/activate
          python3 -m pytest -v tests/test_dice.py
      - name: Heroku deploying production
        if: success()
        uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_app_name: ci-me-dice-production
          heroku_email: "salitomeyo16@gmail.com"
          heroku_api_key: ${{secrets.HEROKU_AUTH_TOKEN}}    
      - name: Success slack notification
        # Pick up events even if the job is success.
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: ci-me-dice-on-demand-salitomeyo
          status: SUCCESS
          color: good

      - name: Failure slack notification
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: ci-me-dice-on-demand-salitomeyo
          status: FAILED
          color: danger
